#!/usr/bin/env node
// The craft map: every craft, what it covers and which guide serves which task, read from
// each super skill's router. The garden planner (../planner/garden) uses it to pick crafts
// and guides for a request that spans several crafts. Generated, so it never drifts.
//
//   node craft-map.mjs           check the planner's craft map is up to date
//   node craft-map.mjs --write   regenerate it
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadChains } from "./chains.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(HERE, "..");
const PATHS = /(?:references|scripts|templates)\/[\w./-]*[\w/]/g;
const START = "<!-- craft-map:start -->", END = "<!-- craft-map:end -->";

function cats(root) {
  const src = fs.readFileSync(path.join(root, "skill-garden.html"), "utf8").match(/const CATS = (\[[\s\S]*?\n\s*\]);/);
  if (!src) throw new Error("CATS not found in skill-garden.html");
  return new Function(`return ${src[1]}`)();
}

/** Rows of a router's "Pick the right guide" section: [{ task, files }]. */
function guides(skill) {
  const sec = skill.split(/^## /m).find((s) => s.startsWith("Pick the right guide")) || "";
  const rows = [];
  for (const line of sec.split("\n")) {
    if (!line.startsWith("|") || /^\|\s*-/.test(line)) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 2 || /^(task|script|need|when)\b/i.test(cells[0])) continue;
    const [a, b] = (cells[0].match(PATHS) && !cells[1].match(PATHS)) ? [cells[1], cells[0]] : [cells[0], cells.slice(1).join(" ")];
    const files = [...new Set(b.match(PATHS) || [])];
    if (files.length) rows.push({ task: a.replace(/\*\*/g, ""), files });
  }
  return rows;
}

export function crafts(root = ROOT) {
  const dir = path.join(root, "superskills");
  return fs.readdirSync(dir).sort().filter((id) => fs.existsSync(path.join(dir, id, "SKILL.md"))).map((id) => {
    const meta = JSON.parse(fs.readFileSync(path.join(dir, id, "topic.json"), "utf8"));
    return { id, name: meta.name, blurb: meta.blurb, guides: guides(fs.readFileSync(path.join(dir, id, "SKILL.md"), "utf8")) };
  });
}

/** { [file]: wanted content } for the planner's generated parts. */
export function render(root = ROOT) {
  const all = crafts(root), byId = Object.fromEntries(all.map((c) => [c.id, c]));
  const groups = cats(root).map((g) => ({ name: g.name, list: g.ids.map((id) => byId[id]).filter(Boolean) }));
  const placed = new Set(groups.flatMap((g) => g.list.map((c) => c.id)));
  const rest = all.filter((c) => !placed.has(c.id));
  if (rest.length) groups.push({ name: "More", list: rest });
  const chains = loadChains(root);

  const table = [
    START,
    "<!-- Generated by local/craft-map.mjs from each router and topic.json. Run: node local/craft-map.mjs --write -->",
    "",
    ...groups.flatMap((g) => [`**${g.name}**`, "", "| Craft | Covers |", "|---|---|", ...g.list.map((c) => `| \`${c.id}\` | ${c.blurb} |`), ""]),
    chains.length ? `**Saved plans (chains):** ${chains.map((c) => `\`${c.id}\` (${c.blurb.replace(/\.$/, "")})`).join("; ")}.` : "",
    END,
  ].join("\n");

  const map = [
    "# Craft map",
    "",
    "<!-- Generated by local/craft-map.mjs from each router's guide table. Don't edit; run: node local/craft-map.mjs --write -->",
    "",
    "Every craft and which of its files serves which task. Paths are inside that craft: with the plugin they sit at `../../superskills/<craft>/<path>` from this planner (or load the skill `skillgarden:<craft>`); on the connector, call `get_guide` with the craft and path.",
    "",
    ...groups.flatMap((g) => [`# ${g.name}`, "", ...g.list.flatMap((c) => [
      `## ${c.id}: ${c.name}`, "", c.blurb, "",
      ...c.guides.map((r) => `- ${r.task} → ${r.files.map((f) => `\`${f}\``).join(", ")}`), "",
    ])]),
  ].join("\n");

  const skillFile = path.join(root, "planner", "garden", "SKILL.md");
  const skill = fs.readFileSync(skillFile, "utf8");
  const i = skill.indexOf(START), j = skill.indexOf(END);
  if (i < 0 || j < i) throw new Error(`${path.relative(root, skillFile)} needs ${START} and ${END}`);
  return {
    [skillFile]: skill.slice(0, i) + table + skill.slice(j + END.length),
    [path.join(root, "planner", "garden", "references", "craft-map.md")]: map,
  };
}

/** Files whose generated part is out of date. */
export function stale(root = ROOT) {
  return Object.entries(render(root)).filter(([f, want]) => !fs.existsSync(f) || fs.readFileSync(f, "utf8") !== want).map(([f]) => path.relative(root, f));
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--write")) {
    for (const [f, want] of Object.entries(render())) { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, want); }
    const all = crafts();
    console.log(`Craft map written: ${all.length} crafts, ${all.reduce((n, c) => n + c.guides.length, 0)} guide rows.`);
    const thin = all.filter((c) => c.guides.length < 3).map((c) => c.id);
    if (thin.length) console.log(`Few guide rows read from: ${thin.join(", ")}`);
  } else {
    const s = stale();
    console.log(s.length ? `Out of date: ${s.join(", ")}. Run: node local/craft-map.mjs --write` : "Craft map up to date.");
    process.exit(s.length ? 1 : 0);
  }
}
